# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Homebox Addon
version: "2.2.0"
slug: homebox
description: Homebox inventory management add-on
url: "https://github.com/Oddiesea/homebox-ha-addon"
arch:
  # - armhf
  # - armv7
  - aarch64
  # - amd64
  # - i386
map:
  - share:rw
image: "ghcr.io/Oddiesea/homebox-ha-addon@sha256:20bb37b46df5536765bdac6652030562a524ec3b72033909955818a27c436cee"
init: false
ingress: true
ingress_port: 7745
# Ports are kept for backwards compatibility but ingress is preferred
ports:
  7745/tcp: 7745
